---
title: "Data Analytics MS FAQ"
output:
  distill::distill_article:
    toc: true
twitter:
  creator: "@JohnHelveston"
base_url: https://www.jhelvy.com
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("R", "functions.R"))
library(distilltools)
```

This page contains information for students in the [Master of Science in Data Analytics program](http://bulletin.gwu.edu/engineering-applied-science/engineering-management-systems-engineering/data-analytics-ms/#requirementstext) at George Washington University. Last Updated: `r Sys.Date()`

- If you have questions about the EMSE track, contact [Prof. John Paul Helveston](mailto:jph@gwu.edu)
- If you have questions about the CS track, contact [Prof. Tim Wood](mailto:timwood@gwu.edu)

> **Important: for student who started BEFORE Fall 2022**: This page reflects the new DA MS course requirements for students starting in Fall 2022 or later. If you are on the old program, then you should check [this Pre-2022 DA MS FAQ](http://faculty.cs.gwu.edu/timwood/old-da-faq).

## Frequently Asked Questions

### What is the recommended sequence for full-time students?

- Semester 1:
    - **CSCI 6444** _Introduction to Big Data and Analytics_
    - **EMSE 6765** _Data Analysis for Engineers and Scientists_
    - **EMSE 6574** _Programming for Analytics_
- Semester 2:
    - **EMSE 6586** _Data Management Systems for Data Analytics_
    - First Required Track Course
        - CS Track: **CSCI 6212** _Design and Analysis of Algorithms_
        - EMSE Track: **EMSE 6575** _Applied Machine Learning for Analytics_
      - **Elective**
- Semester 3:
    - Second Required Track Course
        - CS Track: **CSCI 6364** _Machine Learning_
        - EMSE Track: **EMSE 6577** _Data-Driven Policy_
    - **Elective**
    - **Elective**
- Semester 4:
    - **SEAS 6402** _Data Analytics Capstone_

This leaves your final semester light on course work, which many students find helpful as they apply for jobs and can focus their time on interview preparation.

**NOTE**: The above schedule is optimized for students starting in a fall semester. If you begin in spring, EMSE 6574 is usually not offered. If you are in the CS track, we recommend taking CSCI 6212 instead, or if you are in the EMSE track you can pick an EMSE course without prerequisites to take as an elective.

### What is the recommended sequence for part-time students taking 6 credits a semester?

- Semester 1:
    - **CSCI 6444** _Introduction to Big Data and Analytics_
    - **EMSE 6574** _Programming for Analytics_
- Semester 2:
    - **EMSE 6765** _Data Analysis for Engineers and Scientists_
    - **EMSE 6586** _Data Management Systems for Data Analytics_
- Semester 3:
    - First Required Track Course (**CSCI 6212** or **EMSE 6575**)
    - **Elective**
- Semester 4:
    - Second Required Track Course (**CSCI 6364** or **EMSE 6577**)
    - **Elective**
- Semester 5:
    - **Elective**
    - **SEAS 6402** _Data Analytics Capstone_

### Can you help me understand the overall degree requirements?

The [full requirements in the Bulletin](http://bulletin.gwu.edu/engineering-applied-science/engineering-management-systems-engineering/data-analytics-ms/#requirementstext) are:

- Complete the five Required Courses
- Complete two Required Track courses for your focus area (CSCI 6212 and CSCI 6364 or EMSE 6575 and EMSE 6577)
- Complete one more Elective course in your track’s department at the 6000+ level
- Complete two additional electives. These can be 6000+ courses from **any** department, but if they are outside of CS or EMSE, then you need to get approval from your advisor first.

### Do I need to take CSCI 6362 Probability for Computer Science as a Prerequisite for CSCI 6364 Machine Learning?

No. This is not required as long as you have a statistics/probability course at the undergraduate level. Taking **EMSE 6765 Data Analysis for Engineers and Scientists will also meet this need.**

### How many courses do I need in my focus area (CS or EMSE)?

You must take at least **3** courses in the track you have selected – two are required and the third is any of your choice from that department.
 
### Can I take course X which is not listed in the degree requirements?

If it is a 6000 level course, then generally yes it can be one of your two unrestricted electives. You should contact your advisor for approval first.

Yes, but you will need to fill out the [CS Department’s Registration help form](go.gwu.edu/csregs). Contact your advisor or cs@gwu.edu for more information.

### Can the SEAS 6402 DA Capstone course only be taken in Spring semesters?

The course is typically only offered in the spring, though some years we also offer a smaller fall section. You should not take 6402 until you have completed the other four required courses. If you start the program in Spring, then we recommend taking it in your 3rd semester (i.e., your second spring, a semester before graduation). If you are not able to take the course at the normal time, you should consult with your advisor **before** your last semester about completing the capstone as an independent project.

### I want to register for a 6000 level course, but I'm restricted, how do I register?

Some courses have restrictions on who can register for a variety of reasons. Often times the restriction is due to missing prerequisite courses or the course is only offered to majors in that field (e.g. most courses in DATS are restricted to DATS majors). In these cases, you typically need to fill out an [RTF](https://registrar.gwu.edu/sites/g/files/zaxdzs2171/f/downloads/RegistrationTransactionForm_March2022.pdf) form. Here are some details:

- For EMSE courses: Fill out an [RTF](https://registrar.gwu.edu/sites/g/files/zaxdzs2171/f/downloads/RegistrationTransactionForm_March2022.pdf) and send it to [Professor Helveston](mailto:jph@gwu.edu) for approval.
- For CSCI courses: Go to the [CS Department’s Registration help form](go.gwu.edu/csregs) and fill out the request form. Dr. Tim Wood will take care of processing the request.
- For any other course: Fill out an [RTF](https://registrar.gwu.edu/sites/g/files/zaxdzs2171/f/downloads/RegistrationTransactionForm_March2022.pdf) and send it to the course instructor for approval. In these cases (especially if it's a course outside of SEAS), also include a message as to why you want to enroll in the course. 

In general, if there are prerequisite issues preventing you from registering, also explain in your email why you should be exempt from the prerequisite (e.g. you have prior experience or have taken a similar course, etc.).

### I'm interested in becoming a Teaching Assistant or Research Assistant, how can I apply for one of these positions? 

GTA (teaching assistantship) positions are limited and typically offered to students later in the program (e.g. year 2) to GTA for a course they've already taken in their first year. There are not many of these available, and many are prioritized for PhD students over MS students since PhDs have longer tenures in SEAS (4-5 years) and because many will be in academic settings in their careers and therefore need more teaching experience. The best advice for these positions is to do an excellent job in the classroom and discuss with each faculty member you take a course with that has a GTA to see if you could take on a GTA position in the future. Directly expressing your interest to the faculty is the best thing you can do.  

GRA (research assistantship) positions are typically arranged on a faculty-by-faculty basis and usually supported by external research funding. The best way to find opportunities is to reach out to individual faculty and ask if there are potential GRA positions in their lab. It is also best to read up on the faculty member you are reaching out to to make sure their lab focuses on a topic that you are interested in and have something to offer. This isn't limited to SEAS - you could be a GRA for a professor in a different school, and it is not strange for a DA student to use their skills in other domains, such as public health, the Elliott School, etc. Again, directly reaching out to faculty members is the best advise for obtaining one of these positions.
