---
title: "Technology Change Lab"
output:
  distill::distill_article:
    toc: true
twitter:
  creator: "@JohnHelveston"
base_url: https://jhelvy.github.io/
preview: images/helveston.png
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("R", "functions.R"))

library(htmltools)
image_width <- 150
```

## Faculty

```{r, echo=FALSE}
image_float_layout(
    src = "images/helveston.jpg",
    width = image_width,
    float = "left",
    title = "### John Paul Helveston, Ph.D.",
    text = "John Paul Helveston is an Assistant Professor in the [Department of Engineering Management and Systems Engineering](http://emse.seas.gwu.edu/) at the [George Washington University](https://www.gwu.edu/). He studies technological change, with a particular interest in accelerating the transition to environmentally sustainable and energy-saving technologies. His research centers around how consumer preferences, market dynamics, and policy affect the emergence of critical technologies, such as electric vehicles and solar energy. He is an expert on China's rapidly emerging electric vehicle industry as well as the critical relationship between the US and China in developing and mass producing low carbon energy technologies. He applies an interdisciplinary approach to research, with expertise in discrete choice modeling and conjoint analysis as well as interview-based case studies. He has conducted extensive fieldwork in China, collaborating with colleagues at Beijing Normal University and China's State Information Center on past projects. He is a fluent speaker of Mandarin Chinese and also an award-winning swing dancer. John holds a Ph.D. and M.S. in [Engineering and Public Policy](https://www.cmu.edu/epp/) from Carnegie Mellon University and a B.S. in [Engineering Science and Mechanics](http://www.beam.vt.edu/) from Virginia Tech.",
)
```

## Ph.D. Students

```{r, echo=FALSE}
image_float_layout(
    src = "images/lab/laura_roberson.jpg",
    width = image_width,
    float = "left",
    title = "### Laura Roberson",
    text = "Laura is a PhD student focusing on consumer acceptance and interaction with innovative technologies, especially in the transportation industry. Her research interests include electric vehicle adoption, innovation developments and policies that promote innovations. She also has 8+ years working for a global automotive manufacturer, giving her a balance of academic and industry knowledge and experience. Laura received her BS in Industrial and Systems Engineering from Virginia Tech and her MS in Systems Engineering from the great GWU EMSE department."
)

image_float_layout(
    src = "images/lab/leah_kaplan.jpg",
    width = image_width,
    float = "left",
    title = "### Leah Kaplan",
    text = "Leah is a Ph.D. student in the Systems Engineering Program at the George Washington University and a National Science Foundation Graduate Research Fellow. Leah graduated summa cum laude with her Bachelor’s in chemical engineering from the University of Arizona before moving to DC to pursue an interest in science policy. Leah interned with the House Committee on Science, Space, and Technology and worked for the Arizona State University Consortium for Science, Policy & Outcomes. Leah’s primary research interest is decision-making under uncertainty related to emerging technologies, with a focus on transportation. She aims to understand how we can leverage technologies for the benefit of, rather than detriment to, society."
)

image_float_layout(
    src = "images/lab/lujin_zhao.jpg",
    width = image_width,
    float = "left",
    title = "### Lujin Zhao (赵鲁晋)",
    text = "Lujin is a Ph.D. student in the Systems Engineering Program at the George Washington University. Lujin received a B.S. in Agricultural and Resources Economics from University of Maryland, a M.S. degree in Economics from Tufts University, and a M.S. degree in Data Analytics from the George Washington University. His interests are China’s EV subsidy policies, environmental impacts from the EV industry, and energy policy. For the past several years, he has been living in the DC area and I really enjoy the summertime here except for that during June, July and August."
)
```

## Masters Students

```{r, echo=FALSE}
image_float_layout(
    src = "images/lab/saurav_pantha.jpg",
    width = image_width,
    float = "left",
    title = "### Saurav Pantha",
    text = "Saurav is a graduate student from Kathmandu, Nepal and is currently earning his MS in Systems Engineering at The George Washington University (GW). Before GW, he worked at a business consulting firm based out of Bangalore, India, helping multiple automotive & banking clients to solve business problems through data analytics solutions. Within Dr. Helveston's lab, he has been supporting multiple research projects by setting up a pipeline for a MySQL database, writing R scripts to clean & wrangle data, and conducting literature surveys. When not in school, he loves to go on treks and watch Manchester United's soccer games live."
)
```

## Undergraduate Students

```{r, echo=FALSE}
image_float_layout(
    src = "images/lab/amelia_jacquat.jpg",
    width = image_width,
    float = "left",
    title = "### Amelia Jacquat",
    text = "Amelia is a sophomore at The George Washington University. Originally from New Orleans, LA, she is pursuing a Bachelors degree in Systems Engineering at the School of Engineering and Applied Sciences. She is also pursuing minors in Computer Science and Theatre. After graduation, she plans on pursuing her Masters degree in Systems Engineering. Amelia is excited to continue learning and growing as a researcher and young professional. She plans on using this valuable research experience in her future endeavors, whatever they may be.")

image_float_layout(
    src = "images/lab/helena_row.jpg",
    width = image_width,
    float = "left",
    title = "### Helena Rowe",
    text = "Helena is an undergraduate student from Marblehead, Massachusetts majoring in Systems Engineering and minoring in Sustainability at The George Washington University. In previous roles, she has worked for a small consulting firm, analyzed market research for a building materials start-up, and researched with a professor about climate change risks in the investment industry. Within Dr. Helveston's lab, she is researching electric vehicle (EV) sales forecasts over time from different organizations. She is seeking to better understand the uncertainty in these forecasts and trends over time, in relation to actual sales, and across different industries."
)
```
