---
title: "Research"
description: I study how consumers, firms, markets, and policy affect technological change, with a focus on accelerating the transition to low-carbon technologies like electric vehicles and renewable energy technologies. I have expertise in choice modeling, programming in R, and the global electric vehicle industry.
output:
  distill::distill_article:
    toc: true
    css:
      - css/jhelvy.css
      - css/small-spacing.css
twitter:
  creator: "@JohnHelveston"
base_url: https://www.jhelvy.com
preview: images/lab/john_helveston.png
---

<!-- Remove margin under list items -->
<style>
d-article ol {
    margin-bottom: 5px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("R", "functions.R"))
pubs <- get_pubs()
```

<center>
`r gscholar_stats("https://scholar.google.com/citations?user=DY2D56IAAAAJ")`
</center>

`r aside_center("Source: Google Scholar")`

<center>

`r htmltools::HTML(paste0(icon_link(icon = "ai ai-google-scholar", text = "Google Scholar", url  = "https://scholar.google.com/citations?user=DY2D56IAAAAJ"), icon_link(icon = "ai ai-orcid", text = "ORCID", url  = "https://orcid.org/0000-0002-2657-9191"), icon_link(icon = "ai ai-researchgate", text = "Research Gate", url = "https://www.researchgate.net/profile/John_Helveston")))`

</center>

<br>

## Featured Peer-Reviewed Publications

<aside>*indicates student advised by Helveston</aside>

`r make_pub_list(pubs, "peer_reviewed", featured = TRUE)`

## Other Peer-Reviewed Publications

`r make_pub_list(pubs, "peer_reviewed")`

## Working Papers & Papers Under Review

`r make_pub_list(pubs, "working")`

## Conference Publications

`r make_pub_list(pubs, "conference")`

## Magazine Publications

`r make_pub_list(pubs, "magazine")`

## Books / Book Chapters

`r make_pub_list(pubs, "book")`

## Theses

`r make_pub_list(pubs, "theses")`

## Opinion Editorials

`r make_pub_list(pubs, "oped")`

## Other Publications

`r make_pub_list(pubs, "other")`

## Software

`r make_pub_list(pubs, "software")`

## Media Coverage

`r make_media_list()`
