---
title: "Teaching"
output:
  distill::distill_article:
    toc: true
twitter:
  creator: "@JohnHelveston"
base_url: https://jhelvy.github.io/
preview: images/helveston.png
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("R", "functions.R"))

library(htmltools)
image_width <- 120
```

## 2020–21

```{r, echo=FALSE}
image_float_layout(
    src   = "images/eda_hex_sticker_square.png",
    width = image_width,
    float = "left",
    title = "### [EMSE 4575: Exploratory Data Analysis](https://eda.seas.gwu.edu/2021-Spring/)",
    text  = 'Spring 2021 | George Washington University\n\n<span style="font-size:0.8rem;">Foundations in exploring and visualizing data in R.</span>'
)

image_float_layout(
    src   = "images/p4a_hex_sticker_square.png",
    width = image_width,
    float = "left",
    title = "### [EMSE 4574: Programming for Analytics](https://p4a.seas.gwu.edu/2020-Fall/)",
    text  = 'Fall 2020 | George Washington University\n\n<span style="font-size:0.8rem;">Foundations in programming and computational thinking for data analytics in R.</span>'
)
```

## 2019–20

```{r, echo=FALSE}
image_float_layout(
    src   = "images/eda_hex_sticker_square.png",
    width = image_width,
    float = "left",
    title = "### [EMSE 4197: Exploratory Data Analysis](https://eda.seas.gwu.edu/2020-Spring/)",
    text  = 'Spring 2020 | George Washington University\n\n<span style="font-size:0.8rem;">Foundations in exploring and visualizing data in R.</span>'
)

image_float_layout(
    src   = "images/p4a_hex_sticker_square.png",
    width = image_width,
    float = "left",
    title = "### [EMSE 6574: Programming for Analytics](https://p4a.seas.gwu.edu/2019-Fall/)",
    text  = 'Fall 2019 | George Washington University\n\n<span style="font-size:0.8rem;">Foundations in programming and computational thinking for data analytics in R.</span>'
)
```

## 2018–19

```{r, echo=FALSE}
image_float_layout(
    title = "### EMSE 6035: Marketing of Technology",
    text  = 'Spring 2019 | George Washington University\n\n<span style="font-size:0.8rem;">Analyzing consumer choice data in R to inform design decisions in an uncertain, competitive, market.</span>'
)
```
