---
title: "ISA Industrial Policy Webinar Series: Taking Charge"
description: |
  I moderated the ISA Webinar on "Batteries for Electric Vehicles and the Transformation of the Automotive Supply Chain"
author: John Paul Helveston
date: "2021-12-01"
preview: "isa.png"
categories:
  - China
  - Technology
twitter:
  creator: "@JohnHelveston"
output:
  distill::distill_article:
    self_contained: false
    toc: false
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
library(metathis)
library(distilltools)

knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.retina = 3,
  comment = "#>"
)

meta() %>%
  meta_description(
    'I moderated the ISA Webinar on "Batteries for Electric Vehicles and the Transformation of the Automotive Supply Chain"'
  ) %>%
  meta_name("github-repo" = "jhelvy/jhelvy.com") %>%
  meta_viewport() %>%
  meta_social(
    title = "ISA Industrial Policy Webinar Series: Taking Charge",
    url = "https://www.jhelvy.com/talks/2021-12-01-isa-battery-webinar",
    image = "https://www.jhelvy.com/talks/2021-12-01-isa-battery-webinar/isa.png",
    image_alt = "Title slide for ISA Webinar",
    og_type = "website",
    og_author = c("John Paul Helveston"),
    twitter_card_type = "summary",
    twitter_creator = "@JohnHelveston"
  )
```

On December 1, 2021, I had the honor of moderating the Industry Studies Association (ISA) webinar on the future of batteries for electric vehicles, as part of its ongoing [webinar series](https://www.industrystudies.org/isa-webinar-series) on industrial policy. You can watch the recording below.

**About the webinar**:

The auto industry is on the cusp of its greatest transformation in more than a century, shifting from internal combustion engines to electric motors powered by lithium-ion batteries. China, which already plays an important role in global auto supply chains, has been the first mover in this transformation, sparking concerns in the United States and elsewhere. This session will explore the United States’ proposed response to this challenge and its profound links to both long-run economic prosperity and the future of the planet.

**Moderator**: [John Paul Helveston](https://www.seas.gwu.edu/john-helveston), Assistant Professor, Engineering Management & Systems Engineering, George Washington University

**Administration Presenter**: [Susan Helper](https://faculty.weatherhead.case.edu/helper/), Senior Economist, White House Council of Economic Advisers

**Discussants**:

- [George W. Crabtree](https://www.anl.gov/profile/george-w-crabtree), Director, Joint Center for Energy Storage Research, Argonne National Laboratory
- [Kristin Dziczek](https://www.cargroup.org/person/kristin-dziczek/), Senior Vice President – Research, Center for Automotive Research
- [John Paul MacDuffie](https://mgmt.wharton.upenn.edu/profile/macduffi/), President, Industry Studies Association, and Professor of Management, University of Pennsylvania

<iframe width="560" height="420" src="https://www.youtube.com/embed/tFqwPABDPkc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
